apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
    tier: database
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: database
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
    spec:
      containers:
        - image: mariadb:latest
          args: 
            - "--ignore-db-dir=lost+found"
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: root
            - name: MARIADB_DATABASE
              value: auth
          ports:
            - containerPort: 13306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mariadb
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: database
spec:
  selector:
    app: mariadb
    tier: database
  ports:
  - port: 13306
    targetPort: 13306
  clusterIP: None
