apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-app
  labels:
    app: auth-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-app
  template:
    metadata:
      labels:
        app: auth-service-app
    spec:
      imagePullSecrets:
        - name: docker-hub-cred
      containers:
        - name: auth-service-app
          image: baaws/auth-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9003
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              value: auth
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  selector:
    app: auth-service-app
  ports:
    - port: 80
      targetPort: 9003
