apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels:
    app: department-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-app
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      imagePullSecrets:
        - name: docker-hub-cred
      containers:
        - name: department-service-app
          image: baaws/department-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: olshop
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root

---

apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
spec:
  selector:
    app: department-service-app
  ports:
    - targetPort: 9001
      port: 80